### //api/login =>ok
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "jeanbon@gmail.com",
    "password": "cuillere"
}


### /api/me => ok
GET http://localhost:3000/api/me
Content-Type: application/json
Authorization:barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDIsIm5hbWUiOiJKZWFuIEJvbiIsImVtYWlsIjoiamVhbmJvbkBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjMyMDUyNzMxLCJleHAiOjE2MzIwNTQ1MzF9.hj-3KmtbYw2_Of42PFZqSH1izRFMyMg6QRIx711d_WQ
